version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgresql
      JAVA_TIMEZONE: Asia/Jakarta
    ports:
      - "3000:3000"
    volumes:
      - /dev/urandom:/dev/random:ro
    networks:
      - local_network

networks:
  local_network:
    external: true
    name: local_network