version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis7.2
    ports:
      - "6379:6379"
    networks:
      - local_network

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - local_network

  mysql:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_db
      MYSQL_USER: dhirawigata
      MYSQL_PASSWORD: dhirawigata
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local_network

  postgresql:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: dhirawigata
      POSTGRES_PASSWORD: dhirawigata
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./../config/postgresql/init/:/docker-entrypoint-initdb.d/ # Mount the initialization script
    networks:
      - local_network

  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq3.12.12
    environment:
      RABBITMQ_DEFAULT_USER: dhirawigata
      RABBITMQ_DEFAULT_PASS: dhirawigata
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - local_network


networks:
  local_network:
    external: true
    name: local_network

volumes:
  mysql_data:
  postgres_data:
  rabbitmq_data: