version: '3.8'

services:
  kong:
    image: kong/kong-gateway:3.5.0.3
    container_name: kong3.5.0.3
    command: "/bin/sh -c 'kong migrations bootstrap && kong start'"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql
      KONG_PG_DATABASE: kong_db
      KONG_PG_USER: kong_user
      KONG_PG_PASSWORD: kong_password
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl' # Open the Admin API port
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    ports:
      - "8000:8000" # Incoming HTTP traffic
      - "8443:8443" # Incoming HTTPS traffic
      - "8444:8444"
      - "8001:8001" # Admin API
      - "8002:8002" # Admin GUI
    networks:
      - local_network

networks:
  local_network:
    external: true
    name: local_network